### PR TITLE
[WIP] Added css-based numeration

### PR DESCRIPTION
**Pull request by jjperezaguinaga**
We need some numeration on the table. Added a css one as an example, but ideally would look better than this.

### CODE REVIEW

**Comment by nionis** [comment]
@jjperezaguinaga not sure I follow why we need this

**Comment by jjperezaguinaga** [comment]
@nionis was a request from our Ambassadors team to easily identify who is in which rank at all times.

image

**Comment by nionis** [comment]
@jjperezaguinaga got it, yeah that makes sense, we just need to make sure the initial view is sorted by score

**Comment by nionis** [comment]
Tackled in https://github.com/hoprnet/hopr-leaderboard/pull/23

**Pull request closed without merging**
